import assert from "node:assert/strict";
import test from "node:test";
import { addToCart, clearCart, emptyCart, getFulfillmentClassification, getItemCount, getSubtotal, removeFromCart, updatePhysicalQuantity, type CatalogLookup } from "../lib/cart/cart.ts";
import { parsePersistedCart } from "../lib/cart/persistence.ts";
import type { Artwork, ArtworkVariant } from "../types/commerce.ts";

const digital: ArtworkVariant = { id: "digital-a", name: "Digital edition", fulfillmentType: "DIGITAL", fulfillmentRequirement: "DIGITAL_DELIVERY", price: { amountMinor: 12000, currency: "USD" }, availability: "AVAILABLE", purchaseAvailability: "PURCHASABLE", commercialConfigurationId: "digital-standard-edition", quantityPolicy: "SINGLE" };
const physical: ArtworkVariant = { id: "physical-a", name: "Canvas edition", fulfillmentType: "PHYSICAL", fulfillmentRequirement: "POD_FULFILLMENT", price: { amountMinor: 28000, currency: "USD" }, availability: "AVAILABLE", purchaseAvailability: "PURCHASABLE", commercialConfigurationId: "canvas-18x24-in", quantityPolicy: "MULTIPLE", size: "18 × 24 in", podMapping: {} };
const unavailable: ArtworkVariant = { ...physical, id: "physical-unavailable", commercialConfigurationId: "canvas-unavailable", purchaseAvailability: "UNAVAILABLE" };
const soldOut: ArtworkVariant = { ...physical, id: "physical-sold-out", commercialConfigurationId: "canvas-sold-out", availability: "SOLD_OUT" };
const artwork: Artwork = { id: "artwork-a", slug: "artwork-a", title: "Artwork A", shortDescription: "", collection: { id: "collection-a", name: "Collection", slug: "collection" }, catalogVisibility: "VISIBLE", pricingStatus: "DEVELOPMENT_PLACEHOLDER", heroImage: { src: "/placeholder.svg", alt: "", width: 1, height: 1 }, galleryImages: [], digitalVariant: digital, physicalVariants: [physical, unavailable, soldOut], featured: false };
const catalog: CatalogLookup = { getVariant: (artworkId, variantId) => artworkId === artwork.id ? (() => { const variant = [artwork.digitalVariant, ...artwork.physicalVariants].find((candidate) => candidate?.id === variantId); return variant ? { artwork, variant } : undefined; })() : undefined };
const select = (variant: ArtworkVariant) => ({ artworkId: artwork.id, variantId: variant.id, commercialConfigurationId: variant.commercialConfigurationId });

test("digital duplicate adds retain one entitlement line", () => { const once = addToCart(emptyCart(), catalog, select(digital)); const twice = addToCart(once, catalog, select(digital)); assert.equal(twice.lines.length, 1); assert.equal(twice.lines[0].quantity, 1); });
test("physical duplicate adds increment quantity and subtotal uses minor units", () => { const state = addToCart(addToCart(addToCart(emptyCart(), catalog, select(digital)), catalog, select(physical)), catalog, select(physical)); assert.equal(getItemCount(state), 3); assert.deepEqual(getSubtotal(state, catalog), { amountMinor: 68000, currency: "USD" }); });
test("remove and clear operate deterministically", () => { const state = addToCart(addToCart(emptyCart(), catalog, select(digital)), catalog, select(physical)); assert.equal(removeFromCart(state, select(digital)).lines.length, 1); assert.deepEqual(clearCart(state), { lines: [], hydrated: false }); });
test("mixed cart fulfillment derives from fulfillment requirements", () => { const state = addToCart(addToCart(emptyCart(), catalog, select(digital)), catalog, select(physical)); assert.equal(getFulfillmentClassification(state), "MIXED"); });
test("malformed persistence falls back safely", () => { assert.deepEqual(parsePersistedCart("not-json"), emptyCart()); assert.deepEqual(parsePersistedCart(JSON.stringify({ version: 99, lines: [] })), emptyCart()); });
test("unavailable variants and invalid quantity changes are rejected", () => { assert.deepEqual(addToCart(emptyCart(), catalog, select(unavailable)), emptyCart()); assert.deepEqual(addToCart(emptyCart(), catalog, select(soldOut)), emptyCart()); const state = addToCart(emptyCart(), catalog, select(physical)); assert.equal(updatePhysicalQuantity(state, catalog, select(physical), 0).lines[0].quantity, 1); const entitlement = addToCart(emptyCart(), catalog, select(digital)); assert.equal(updatePhysicalQuantity(entitlement, catalog, select(digital), 2).lines[0].quantity, 1); });