import Image from "next/image";
import Link from "next/link";
import { ArtworkGrid } from "@/components/artwork/artwork-grid";
import { Container } from "@/components/ui/container";
import { Eyebrow } from "@/components/ui/eyebrow";
import { Section } from "@/components/ui/section";
import { SectionHeading } from "@/components/ui/section-heading";
import { featuredArtworks, launchCollection } from "@/data/artworks";

export function HomePage() {
  return <><Section className="overflow-hidden border-b border-[var(--color-line)] pb-12 pt-14 sm:pb-20 sm:pt-24"><Container><div className="grid items-end gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.62fr)]"><div className="max-w-4xl"><Eyebrow>Private digital gallery</Eyebrow><h1 className="mt-6 font-serif text-[clamp(3.7rem,10vw,8.5rem)] leading-[0.82] tracking-[-0.055em] text-[var(--color-ink)]">Enter the<br /><em className="font-normal text-[var(--color-gold)]">Sanctuary.</em></h1><p className="mt-9 max-w-xl text-base leading-8 text-[var(--color-muted)] sm:text-lg">A considered space for contemporary fine-art editions, where each work is given room to hold its own presence.</p><Link href="/collections" className="action-link">View the collection <span>↗</span></Link></div><div className="border border-[var(--color-line)] bg-[var(--color-surface)] p-3"><Image src={featuredArtworks[0].heroImage.src} alt={featuredArtworks[0].heroImage.alt} width={featuredArtworks[0].heroImage.width} height={featuredArtworks[0].heroImage.height} priority className="h-auto w-full" /></div></div></Container></Section><Section><Container><div className="flex flex-col justify-between gap-8 pb-12 sm:flex-row sm:items-end"><SectionHeading eyebrow="Selected works" title="The launch collection">An opening suite of works, presented as a developing catalogue.</SectionHeading><Link href="/collections" className="nav-link self-start text-[var(--color-gold)] sm:self-auto">See all works ↗</Link></div><ArtworkGrid artworks={featuredArtworks} /></Container></Section><Section className="border-y border-[var(--color-line)] bg-[var(--color-surface)]"><Container><div className="grid gap-10 lg:grid-cols-2 lg:gap-24"><Eyebrow>Our point of view</Eyebrow><p className="font-serif text-4xl leading-[1.04] tracking-[-0.03em] text-[var(--color-ink)] sm:text-5xl">Art deserves a slower encounter: fewer distractions, greater attention, and space enough to stay with what moves you.</p></div></Container></Section><Section><Container><div className="grid gap-12 lg:grid-cols-2 lg:gap-24"><SectionHeading eyebrow="Collection note" title={launchCollection.name}>{launchCollection.description}</SectionHeading><div className="border-l border-[var(--color-gold)] pl-6 text-lg leading-8 text-[var(--color-muted)]">Digital editions and physical canvas editions will be available from a single artwork record, allowing the work—not the fulfillment path—to remain at the center.</div></div></Container></Section><Section className="pt-0"><Container><div className="border border-[var(--color-line)] p-8 sm:p-12"><SectionHeading eyebrow="Artist & vision" title="A practice in quiet attention">Artist statement and biographical material will be supplied by S4R Fine Art.</SectionHeading><Link href="/artist" className="action-link">Meet the vision <span>↗</span></Link></div></Container></Section></>;
}
